version: 2.1
executors:
  ci-executor:
    machine:
      image: circleci/classic:201808-01

commands:
  getdependencies:
    description: "Download and cache all the necessary dependencies"
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            # Perform a Partial Cache Restore (https://circleci.com/docs/2.0/caching/#restoring-cache)
            - v1-dependencies-
      - run:
          name: Setup NVM
          command: |
            echo 'export NVM_DIR="/opt/circleci/.nvm"' >> $BASH_ENV
            echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
      - run:
          name: Install Node 12.16.1
          command: |
            nvm install 12.16.1
            nvm alias default 12.16.1
      - run:
          name: Print Node Version
          command: 'node -v'
      - run:
          name: Print NPM Version
          command: 'npm -v'
      - run:
          name: Install Node Modules
          command: 'npm install'
      - save_cache:
          paths:
            - node
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
   
jobs:
    build:
        executor: ci-executor
        steps:
            - getdependencies
            - run:
                name: build
                command: 'npm build'
    run-test:
        executor: ci-executor
        steps:
            - getdependencies
            - run:
                name: Run Tests
                command: echo 'npm run test'

workflows:
  version: 2
  Build_Test_:
    jobs:
      - build
      - run-test:
          requires:
            - build
